[[CURRENCIES]]
code="ETH"
issuer="GDGUKBXS3W7YVVKZK43MPAHRP6PPZBTTCUY35OIV5NATN3ERBJLEOJHT"
name="ETH Test Token"
desc="This is a test ETH token created for Pi Testnet."
image="https://88eth888.github.io/eth.png"
